apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuguru-deployment
  labels:
    menuguru.fiapprj.perisatto.com/name: service
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      menuguru.fiapprj.perisatto.com/name: service
  template:
    metadata:
      name: menuguru-deployment
      labels:
        menuguru.fiapprj.perisatto.com/name: service
    spec:           
      containers:
        - name: menuguru-service
          image: rperisatto/menuguru-api_service:{{ .Values.image.tag }}
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: menuguru-api-config
                  key: mysql_url
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: menuguru-secret
                  key: mysql_user      
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: menuguru-secret
                  key: mysql_password
          ports:
            - containerPort: 8080      
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60