#Caso esteja executando com o Autoscaling desabilitado, especifique o número de replicas
replicaCount: 1

image:
  tag: "fase2"

service:
  #Para executar de forma local, altere o "type" para "NodePort"
  type: LoadBalancer
  port: 8080
  cloud: aws

autoscaling:
  #Para habilitar o autoscaling, altere a variavel "enable" para "true" ("replicaCount" será ignorado)
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
#Configurações da instância MySQL
mysqlUrl: menuguru.colutxzfkhpm.us-east-1.rds.amazonaws.com
mysqlPort: 3306
mysql_user: cm9vdA==
mysql_password: Skx5NUVZYm9id0NUdkl1WUZPY3g=

#Configurações do provedor de pagamentos (Mercado Pago)
payment_userId: MTg5MTg0MDUxNg==
payment_accessToken: QmVhcmVyIEFQUF9VU1ItODE4MTAyODMzMzEwNDEzMy0wNzA3MjEtMjQxYjk2NGQ1ZmUzMTI2ZmFiZjFiZGM0NGZlYWZmZGUtMTg5MTg0MDUxNg==
payment_hostWebhook: http://ae4c7e1e49a8149bfb99b3e3c589c1c4-cbfc09fb0678a7ed.elb.us-east-1.amazonaws.com:8080